# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #18120b
foreground            #ede0d4

cursor                #f3bd6e
cursor_text_color     #442b00

selection_background  #56442a
selection_foreground  #fadebc

url_color             #b7cea2

# Black
color0   #251f17
color8   #2f2921

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #b7cea2
color10  #394c2a

# Yellow
color3   #ddc2a1
color11  #56442a

# Blue
color4   #f3bd6e
color12  #624000

# Magenta
color5   #d3eabc
color13  #d3eabc

# Cyan
color6   #7f560f
color14  #ffddb1

# White
color7   #d3c4b4
color15  #ede0d4

# Tabs
active_tab_background   #624000
active_tab_foreground   #ffddb1
inactive_tab_background #251f17
inactive_tab_foreground #d3c4b4
tab_bar_background      #18120b
