# --- INPUT CONFIG ---

input {
    # CHANGE THIS: 'es' was the problem. 'us' is the standard.
    kb_layout = us
    
    # Mouse settings (Adjusted so it's not sluggish)
    follow_mouse = 1
    sensitivity = 0.4 # 0 is neutral. -1.0 is slowest, 1.0 is fastest.

    touchpad {
        # 'true' feels more natural (like a phone), change to 'false' if you hate it.
        natural_scroll = true
        tap-to-click = true
        middle_button_emulation = true
    }
}


